type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{endpoint}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {username}
password: {password}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
use_dist_in_explain: true
works:
    work:
        time_secs: 30
        rate: unlimited
        warmup: 10
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table IF EXISTS wide_blob_table;
            - CREATE TABLE wide_blob_table (
                int_col1 INT PRIMARY KEY,
                int_col2 INT,
                blob1 BYTEA,
                blob2 BYTEA,
                blob3 BYTEA,
                blob4 BYTEA,
                blob5 BYTEA,
                blob6 BYTEA,
                blob7 BYTEA,
                blob8 BYTEA,
                blob9 BYTEA,
                blob10 BYTEA
              );

        afterLoad:
            - CREATE INDEX idx_int_col2 ON wide_blob_table(int_col2);

        loadRules:
            - table: wide_blob_table
              count: 1
              rows: 1000000
              columns:
                - name: int_col1
                  count: 1
                  util: PrimaryIntGen
                  params: [1, 1000000]
                - name: int_col2
                  count: 1
                  util: PrimaryIntGen
                  params: [1, 1000000]
                - name: blob1
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob2
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob3
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob4
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob5
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob6
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob7
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob8
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob9
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]
                - name: blob10
                  count: 1
                  util: RandomBytea
                  params: [500000, 1000000]

        executeRules:
            - workload: select_by_index
              time_secs: 30
              run:
                - name: select_by_index
                  weight: 100
                  queries:
                    - query: SELECT * FROM wide_blob_table WHERE int_col2 = ?
                      bindings:
                        - util: CyclicSeqIntGen
                          params: [1, 1000000]
