type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{endpoint}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=true
username: {username}
password: {password}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
use_dist_in_explain: true
works:
    work:
        time_secs: 30
        rate: unlimited
        warmup: 10
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - drop table IF EXISTS wide_table;
            - CREATE TABLE wide_table (
                int_col1 INT PRIMARY KEY,
                int_col2 INT,
                text_col1 TEXT,
                text_col2 TEXT,
                text_col3 TEXT,
                text_col4 TEXT,
                text_col5 TEXT,
                text_col6 TEXT,
                text_col7 TEXT,
                text_col8 TEXT,
                text_col9 TEXT,
                text_col10 TEXT,
                );

        afterLoad:
            - CREATE INDEX idx_int_col2 ON wide_table(int_col2);

        loadRules:
            - table: wide_table
              rows: 10000
              columns:
                  - name: int_col1
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: int_col2
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: text_col
                    count: 10
                    util: RandomAString
                    params: [5000, 5000]

        executeOnce:
            - workload: scan_table
              time_secs: 30
              run:
                  - name: scan_full_table
                    weight: 100
                    queries:
                         query: SELECT * FROM wide_table;
