type: YUGABYTE
createdb: drop database if exists cyugabyte; create database cyugabyte with colocated=true;
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password:
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
works:
    work:
        time: 5
        active_terminals: 1
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBMicroBenchmarkInsertsSequential
    properties:
        setAutoCommit : true
        create :
            - DROP PROCEDURE if exists insert_demo;
            - CREATE PROCEDURE insert_demo(_numRows int)
              LANGUAGE plpgsql
              AS $$
              DECLARE
              BEGIN
              insert into demo (id, col1, col2, col3, col4, col5, col6, col7, col8, col9, col10) select n, n, n+100, n*10+1, n-45, n, n, n*50, n*10, n+1111, n from generate_series(1,_numRows) n;
              END;
              $$;
            - drop table if exists demo;
            - create table demo (id int primary key, col1 int, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);
